# Generated by Django 4.1.13 on 2024-04-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_recommandation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='type',
        ),
    ]
