# Generated by Django 4.1.13 on 2024-04-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_logement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stage', models.IntegerField(choices=[(1, 'ouvrier'), (2, 'technicien'), (3, 'PFE')])),
                ('societe', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('sujet', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('specialiste', models.CharField(max_length=255)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
        ),
    ]
