# Generated by Django 4.1.13 on 2024-04-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.evenement')),
            ],
        ),
    ]
