# Generated by Django 4.1.13 on 2024-04-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_eventsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.evenement')),
            ],
        ),
    ]
