# Generated by Django 4.1.13 on 2024-04-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_stage_type_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='St',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('sujet', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('specialiste', models.CharField(max_length=255)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
