# Generated by Django 4.1.13 on 2024-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_stage_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
