# Generated by Django 3.1.14 on 2024-04-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='capacite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='evenement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.evenement'),
        ),
    ]
