# Generated by Django 3.1.14 on 2024-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20240421_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='capacite',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='evenement',
        ),
        migrations.AddField(
            model_name='evenement',
            name='reserved_seats',
            field=models.IntegerField(default=0),
        ),
    ]
