# Generated by Django 3.1.14 on 2024-04-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20240422_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='reserved_seats',
        ),
    ]
