# Generated by Django 3.1.14 on 2024-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20240427_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logement',
            name='reserved_seats',
            field=models.IntegerField(default=0),
        ),
    ]
