# Generated by Django 3.1.14 on 2024-04-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_reservationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.evenement'),
        ),
    ]
