# Generated by Django 3.1.14 on 2024-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_reservation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reserved_seats',
            field=models.IntegerField(default=0),
        ),
    ]
