# Generated by Django 3.1.14 on 2024-04-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_reservation_trasnport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='trasnport',
            new_name='transport',
        ),
    ]
