# Generated by Django 3.1.14 on 2024-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20240428_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_sieges',
            field=models.IntegerField(default=0),
        ),
    ]
