# Generated by Django 3.1.14 on 2024-04-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_evenement_nombre_sieges'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='nombre_sieges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Logement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.logement'),
        ),
    ]
