# Generated by Django 3.1.14 on 2024-04-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20240428_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Logement',
            new_name='logement',
        ),
    ]
