# Generated by Django 3.1.14 on 2024-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20240428_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='reserved_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logement',
            name='nombre_sieges',
            field=models.IntegerField(null=True),
        ),
    ]
