# Generated by Django 3.1.14 on 2024-04-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20240429_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stage'),
        ),
    ]
