# Generated by Django 3.1.14 on 2024-04-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_reservation_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationhistory',
            name='logement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.logement'),
        ),
    ]
