# Generated by Django 3.1.14 on 2024-04-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_reservationhistory_logement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationhistory',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.stage'),
        ),
    ]
