# Generated by Django 3.1.14 on 2024-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_privatemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='subject',
        ),
    ]
